{% set version = "1.4.3" %}
package:
  name: spark-testing-base
  version: {{ version }}

source:
  url: https://github.com/holdenk/spark-testing-base/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c1effe58439cec5db6679ed4c1ef71967c7ff8865eae5cac9a8d952c0785820d

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - setuptools
    - unittest2
    - findspark
    - pytest
    - pip
  run:
    - python
    - unittest2
    - findspark
    - pytest

test:
  requires:
    - pyspark
  imports:
    - sparktestingbase
    - sparktestingbase.test

about:
  home: https://github.com/holdenk/spark-testing-base
  license: Apache-2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Spark testing for python
  description: Base classes to use when writing tests with Spark
  dev_url: https://github.com/holdenk/spark-testing-base

extra:
  recipe-maintainers:
    - dbast
