{% set name = "spark-testing-base" %}
{% set version = "0.11.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  'sha256': '0428d97e26e3408c17604965b980ceae7140bb55c7619ca50f50a667b5f41eb4'

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - setuptools
    - unittest2
    - findspark
    - pytest
    - pip
  run:
    - python
    - unittest2
    - findspark
    - pytest

test:
  requires:
    - pyspark
  imports:
    - sparktestingbase
    - sparktestingbase.test

about:
  home: https://github.com/holdenk/spark-testing-base
  license: Apache-2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Spark testing for python
  description: Base classes to use when writing tests with Spark
  dev_url: https://github.com/holdenk/spark-testing-base

extra:
  recipe-maintainers:
    - dbast
